#!/usr/bin/env sage -python
"""Scan shifted-derivative F5 sources across the four obvious quotient characters.

For a saved degree-12 quotient q and

    g_a(u) = (u-a) q'(u),

the rational norm of g_a is disc(q) q(a), up to an irrelevant sign.  The
previous scan only retained q(a) in the squareclass of q(0).  Here we also
test the other three squareclasses generated by q(0) and disc(q).  These are
the trivial, discriminant, source-norm, and their product characters.

This is an offline arithmetic sieve.  It does not update the ledger or submit.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import sqlite3
import time
from pathlib import Path

import gmpy2
import numpy as np
from sage.all import PolynomialRing, ZZ


ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT = (
    ROOT / "data" / "gold_f5_f6_20260728_all_character_derivative_scan.json"
)
PRIMES = (3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41)


def exact_value(coefficients: tuple[int, ...], a: int) -> gmpy2.mpz:
    value = gmpy2.mpz(0)
    aa = gmpy2.mpz(a)
    for coefficient in reversed(coefficients):
        value = value * aa + coefficient
    return value


def load_current_tc0() -> set[tuple[str, int]]:
    connection = sqlite3.connect(
        f"file:{(ROOT / 'data' / 'ledger.sqlite3').resolve()}?mode=ro", uri=True
    )
    try:
        return {
            (str(label), int(r))
            for label, r in connection.execute(
                """
                SELECT t.label,t.r
                FROM targets AS t
                WHERE t.team_count=0 AND t.discovered=0
                  AND NOT EXISTS(
                    SELECT 1 FROM baseline_pairs AS b
                    WHERE b.label=t.label AND b.r=t.r
                  )
                  AND NOT EXISTS(
                    SELECT 1 FROM verifications AS v
                    WHERE v.label=t.label AND v.r=t.r AND v.scoreable=1
                  )
                """
            )
        }
    finally:
        connection.close()


def load_sources(current_tc0: set[tuple[str, int]]) -> list[dict]:
    by_hash: dict[str, dict] = {}
    pattern = (
        ROOT
        / "data"
        / "agent_f5_full_ledger_pair_product_routes_shard*of4.jsonl"
    )
    for name in sorted(glob.glob(str(pattern))):
        path = Path(name)
        for line_number, line in enumerate(path.read_text().splitlines(), 1):
            if not line.strip():
                continue
            row = json.loads(line)
            source = row["source"]
            action = row["action"]
            target_label = str(action["targetLabel"])
            if not any(label == target_label for label, _r in current_tc0):
                continue
            quotient_line = str(source["quotientLine"])
            digest = hashlib.sha256(quotient_line.encode()).hexdigest()
            if digest != str(source["quotientPolynomialSha256"]):
                raise ValueError(f"quotient hash mismatch in {path}:{line_number}")
            saved = by_hash.setdefault(
                digest,
                {
                    "coefficientLine": quotient_line,
                    "coefficientSha256": digest,
                    "quotientT12": int(action["quotientT12"]),
                    "rows": [],
                },
            )
            if int(saved["quotientT12"]) != int(action["quotientT12"]):
                raise ValueError("one quotient polynomial has inconsistent actions")
            saved["rows"].append({"action": action, "source": source})
    return sorted(by_hash.values(), key=lambda row: row["coefficientSha256"])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bound", type=int, default=200_000)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    if args.bound < 1:
        raise ValueError("bound must be positive")
    if args.output.exists():
        raise FileExistsError(f"refusing to overwrite {args.output}")

    started = time.monotonic()
    current_tc0 = load_current_tc0()
    sources = load_sources(current_tc0)
    if args.limit is not None:
        sources = sources[: args.limit]
    integers = np.arange(-args.bound, args.bound + 1, dtype=np.int64)
    residue_indexes = {prime: integers % prime for prime in PRIMES}
    ring = PolynomialRing(ZZ, "y")
    hits = []
    exact_checks = 0
    sieve_survivors = 0

    for position, source in enumerate(sources, 1):
        coefficients = tuple(
            int(value) for value in source["coefficientLine"].split(",")
        )
        if len(coefficients) != 13 or coefficients[-1] != 1:
            raise ValueError("bad saved quotient polynomial")
        polynomial = ring([ZZ(value) for value in coefficients])
        discriminant = int(polynomial.discriminant())
        q0 = int(coefficients[0])
        # Keep the full integer representatives during the sieve.  Factoring
        # hundreds of degree-12 discriminants merely to strip square factors
        # is vastly more expensive and is unnecessary for the exact predicate
        # q(a)*multiplier in Z^2.
        source_norm_core = int(ZZ(q0).squarefree_part())
        characters = (
            ("trivial", 1, discriminant),
            ("source_norm", q0, source_norm_core * discriminant),
            ("discriminant", discriminant, 1),
            (
                "source_norm_times_discriminant",
                q0 * discriminant,
                source_norm_core,
            ),
        )

        residues = {
            prime: np.arange(prime, dtype=np.int64) for prime in PRIMES
        }
        values_mod = {}
        for prime in PRIMES:
            values = np.zeros(prime, dtype=np.int64)
            for coefficient in reversed(coefficients):
                values = (values * residues[prime] + coefficient % prime) % prime
            values_mod[prime] = values

        for kind, multiplier, derivative_core_representative in characters:
            mask = np.ones(integers.shape, dtype=np.bool_)
            mask[args.bound] = False
            for prime in PRIMES:
                products = values_mod[prime] * (multiplier % prime) % prime
                allowed = np.fromiter(
                    (
                        product == 0
                        or pow(int(product), (prime - 1) // 2, prime) == 1
                        for product in products
                    ),
                    dtype=np.bool_,
                    count=prime,
                )
                mask &= allowed[residue_indexes[prime]]
                if not mask.any():
                    break
            candidates = integers[mask]
            sieve_survivors += int(candidates.size)
            mm = gmpy2.mpz(multiplier)
            for a_value in candidates:
                a = int(a_value)
                qa = exact_value(coefficients, a)
                product = qa * mm
                exact_checks += 1
                if product <= 0 or not gmpy2.is_square(product):
                    continue
                hits.append(
                    {
                        "a": a,
                        "characterKind": kind,
                        "characterMultiplier": str(multiplier),
                        "derivativeNormCoreRepresentative": str(
                            derivative_core_representative
                        ),
                        "qAtA": str(qa),
                        "source": source,
                        "squareRootOfProduct": str(gmpy2.isqrt(product)),
                    }
                )
        if position % 50 == 0 or position == len(sources):
            print(
                json.dumps(
                    {
                        "event": "progress",
                        "hits": len(hits),
                        "position": position,
                        "sources": len(sources),
                    },
                    sort_keys=True,
                ),
                flush=True,
            )

    document = {
        "schemaVersion": "gold-f5-f6-all-character-derivative-scan-v1",
        "bound": args.bound,
        "characterSpan": [
            "1",
            "q(0)",
            "disc(q)",
            "q(0)*disc(q)",
        ],
        "currentTc0Definition": (
            "team_count=0, discovered=0, nonbaseline, locally unowned"
        ),
        "elapsedSeconds": round(time.monotonic() - started, 3),
        "exactChecks": exact_checks,
        "hits": hits,
        "networkCalls": 0,
        "primes": list(PRIMES),
        "sieveSurvivors": sieve_survivors,
        "sourceCount": len(sources),
        "submissionCalls": 0,
    }
    args.output.write_text(
        json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "event": "complete",
                "hits": len(hits),
                "output": str(args.output),
                "sourceCount": len(sources),
            },
            sort_keys=True,
        ),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
