#!/usr/bin/env sage -python
"""Scan two-linear-factor derivative radicands across quotient characters.

For g(u)=(u-a)(u-b)q'(u), the rational norm is
disc(q)q(a)q(b), up to sign.  A rank-11 character lift is possible whenever
q(a)q(b) lies in one of the four squareclasses generated by q(0) and disc(q).
This bounded offline scan records all exact squareclass hits.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import time
from itertools import combinations
from pathlib import Path

import gmpy2
from sage.all import PolynomialRing, ZZ


ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
DEFAULT_OUTPUT = (
    DATA / "gold_f5_f6_20260728_two_shift_character_scan.json"
)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


SINGLE = load_module(
    "gold_single_character_scan",
    ROOT / "gold_f5_f6_20260728_all_character_derivative_scan.sage.py",
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bound", type=int, default=30)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if args.bound < 1:
        raise ValueError("bound must be positive")
    if args.output.exists():
        raise FileExistsError(f"refusing to overwrite {args.output}")

    started = time.monotonic()
    current_tc0 = SINGLE.load_current_tc0()
    sources = SINGLE.load_sources(current_tc0)
    if args.limit is not None:
        sources = sources[: args.limit]
    ring = PolynomialRing(ZZ, "y")
    parameters = tuple(
        value for value in range(-args.bound, args.bound + 1) if value != 0
    )
    hits = []
    exact_checks = 0

    for position, source in enumerate(sources, 1):
        coefficients = tuple(
            int(value) for value in source["coefficientLine"].split(",")
        )
        polynomial = ring([ZZ(value) for value in coefficients])
        discriminant = int(polynomial.discriminant())
        q0 = int(coefficients[0])
        source_norm_core = int(ZZ(q0).squarefree_part())
        characters = (
            ("trivial", 1, discriminant),
            ("source_norm", q0, source_norm_core * discriminant),
            ("discriminant", discriminant, 1),
            (
                "source_norm_times_discriminant",
                q0 * discriminant,
                source_norm_core,
            ),
        )
        values = {
            a: SINGLE.exact_value(coefficients, a) for a in parameters
        }
        seen = set()
        for a, b in combinations(parameters, 2):
            qab = values[a] * values[b]
            if qab == 0:
                continue
            for kind, multiplier, derivative_core in characters:
                exact_checks += 1
                product = qab * gmpy2.mpz(multiplier)
                if product <= 0 or not gmpy2.is_square(product):
                    continue
                key = (a, b, int(derivative_core))
                if key in seen:
                    continue
                seen.add(key)
                hits.append(
                    {
                        "a": a,
                        "b": b,
                        "characterKind": kind,
                        "characterMultiplier": str(multiplier),
                        "derivativeNormCoreRepresentative": str(
                            derivative_core
                        ),
                        "qAtA": str(values[a]),
                        "qAtB": str(values[b]),
                        "source": source,
                        "squareRootOfProduct": str(gmpy2.isqrt(product)),
                    }
                )
        if position % 25 == 0 or position == len(sources):
            print(
                json.dumps(
                    {
                        "event": "progress",
                        "hits": len(hits),
                        "position": position,
                        "sources": len(sources),
                    },
                    sort_keys=True,
                ),
                flush=True,
            )

    payload = {
        "schemaVersion": "gold-f5-f6-two-shift-character-scan-v1",
        "bound": args.bound,
        "characterSpan": ["1", "q(0)", "disc(q)", "q(0)*disc(q)"],
        "elapsedSeconds": round(time.monotonic() - started, 3),
        "exactChecks": exact_checks,
        "hits": hits,
        "networkCalls": 0,
        "parameterCount": len(parameters),
        "sourceCount": len(sources),
        "submissionCalls": 0,
    }
    args.output.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "event": "complete",
                "hits": len(hits),
                "output": str(args.output),
                "sourceCount": len(sources),
            },
            sort_keys=True,
        ),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
