#!/usr/bin/env sage
"""Search exact nested-D4 quartic lifts over certified sextic quotients.

For a sextic field K=Q(y) and a,b in K, the relative quartic

    X^4 - 2*a*X^2 + a^2 - b

is generated by sqrt(a + sqrt(b)) and generically has D4 normal closure
over K.  Its norm to Q has degree 24.  This offline pilot matches signatures
and Frobenius profiles against the current Alex-only 6-by-4, 4T3-fiber
targets.  It never stages or submits.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import time
from collections import Counter
from functools import reduce
from math import gcd, lcm
from pathlib import Path

from sage.all import GF, PolynomialRing, QQ, ZZ, libgap, pari, prime_range


ROOT = Path(__file__).resolve().parent
BASES = ROOT / "data" / "agent_non12_recoverable_subfields.jsonl"
PLACEMENTS = ROOT / "data" / "current_rank11_alex_20260812_unique_placements.jsonl"
BLOCK_CENSUS = ROOT / "data" / "current_rank11_alex_block_census_20260814.jsonl"
RECOVERY_TARGETS = ROOT / "data" / "current_allgen_signature_recovery_targets_20260813.json"


def coefficient_line(polynomial):
    return ",".join(str(ZZ(value)) for value in polynomial.list())


def integral_monic_scale(polynomial, ring):
    polynomial = ring(polynomial)
    if polynomial.leading_coefficient() != 1:
        polynomial = polynomial / polynomial.leading_coefficient()
    degree = int(polynomial.degree())
    denominator = 1
    for coefficient in polynomial.list():
        denominator = lcm(denominator, int(QQ(coefficient).denominator()))
    coefficients = []
    for index, coefficient in enumerate(polynomial.list()):
        value = QQ(coefficient) * denominator ** (degree - index)
        if value.denominator() != 1:
            raise ArithmeticError("integral scaling failed")
        coefficients.append(ZZ(value))
    candidate = ring(coefficients)
    if candidate.degree() != degree or candidate.leading_coefficient() != 1:
        return None
    return candidate


def cycle_type(polynomial, prime):
    reduced = polynomial.change_ring(GF(prime))
    if not reduced.is_squarefree():
        return None
    return tuple(
        sorted(
            int(factor.degree())
            for factor, exponent in reduced.factor()
            for _ in range(int(exponent))
        )
    )


def group_cycle_profiles(t):
    group = libgap.TransitiveGroup(24, int(t))
    points = libgap.eval("[1..24]")
    return {
        tuple(
            sorted(
                int(value)
                for value in libgap.CycleLengths(
                    libgap.Representative(conjugacy_class), points
                )
            )
        )
        for conjugacy_class in libgap.ConjugacyClasses(group)
    }


def load_targets(quotient_label, universe_path=None, recovery_path=None):
    if universe_path is not None:
        if recovery_path is None:
            raise ValueError("universe matching requires --recovery-targets")
        recovery = json.loads(recovery_path.read_text(encoding="utf-8"))
        pair_rs = {}
        for row in recovery.values():
            pair_rs.setdefault(str(row["label"]), set()).add(int(row["r"]))
        universe = json.loads(universe_path.read_text(encoding="utf-8"))
        return [
            {
                "label": str(row["label"]),
                "pairRs": pair_rs[str(row["label"])],
                "cycleProfiles": {
                    tuple(int(value) for value in profile)
                    for profile in row["cycleProfiles"]
                },
                "groupOrder": int(row["order"]),
                "blockKernelOrder": max(
                    [int(value) for value in row.get("kernelOrders", [])] or [0]
                ),
            }
            for row in universe["groups"]
            if str(row["label"]) in pair_rs
        ]
    placements = [
        json.loads(line)
        for line in PLACEMENTS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    pair_rs = {}
    for row in placements:
        pair_rs.setdefault(str(row["label"]), set()).add(int(row["r"]))
    census = [
        json.loads(line)
        for line in BLOCK_CENSUS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    targets = []
    for row in census:
        system = next(
            (
                item
                for item in row["blockSystems"]
                if item["shape"] == "6x4"
                and item["fiberActionLabel"] == "4T3"
                and item["quotientActionLabel"] == quotient_label
            ),
            None,
        )
        label = str(row["label"])
        if system is None or label not in pair_rs:
            continue
        targets.append(
            {
                "label": label,
                "pairRs": pair_rs[label],
                "cycleProfiles": group_cycle_profiles(int(row["t"])),
                "groupOrder": int(row["groupOrder"]),
                "blockKernelOrder": int(system["blockKernelOrder"]),
            }
        )
    return targets


def load_bases(path, quotient_label, limit, offset):
    result = []
    seen = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if (
            row.get("galoisGroup", {}).get("label") != quotient_label
            or int(row.get("subfieldDegree", -1)) != 6
        ):
            continue
        coefficients = str(row["coefficientLine"])
        if coefficients in seen:
            continue
        seen.add(coefficients)
        if len(seen) <= offset:
            continue
        result.append(
            {
                "coefficientLine": coefficients,
                "coefficientSha256": str(row["coefficientSha256"]),
                "realRoots": int(row["realRoots"]),
                "sourceLabel": str(row["sourceLabel"]),
            }
        )
        if len(result) >= limit:
            break
    return result


def coefficient_forms(bound, extra, seed):
    values = {
        (constant, 0, 0, 0, 0, 0)
        for constant in range(-bound, bound + 1)
        if constant
    }
    for c0 in range(-bound, bound + 1):
        for sign in (-1, 1):
            values.add((c0, sign, 0, 0, 0, 0))
            values.add((c0, 0, sign, 0, 0, 0))
            values.add((c0, sign, sign, 0, 0, 0))
    rng = random.Random(seed)
    while len(values) < extra + 1 + 6 * (2 * bound + 1):
        coefficients = tuple(rng.randint(-bound, bound) for _ in range(6))
        if sum(value != 0 for value in coefficients) >= 2:
            values.add(coefficients)
    result = sorted(values)
    rng.shuffle(result)
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--bases", type=Path, default=BASES)
    parser.add_argument("--quotient-label", required=True)
    parser.add_argument("--universe-profiles", type=Path)
    parser.add_argument("--recovery-targets", type=Path, default=RECOVERY_TARGETS)
    parser.add_argument("--base-limit", type=int, default=1)
    parser.add_argument("--base-offset", type=int, default=0)
    parser.add_argument("--coefficient-bound", type=int, default=2)
    parser.add_argument("--form-extra", type=int, default=64)
    parser.add_argument("--form-seed", type=int, default=1)
    parser.add_argument("--a-mode", choices=("all", "constant"), default="all")
    parser.add_argument("--b-mode", choices=("all", "constant"), default="all")
    parser.add_argument("--prime-max", type=int, default=997)
    parser.add_argument("--max-candidates", type=int, default=5000)
    parser.add_argument("--max-wall-seconds", type=int, default=3600)
    parser.add_argument("--skip-reduction", action="store_true")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists() or args.summary.exists():
        raise FileExistsError("refusing to overwrite output")

    targets = load_targets(
        args.quotient_label,
        universe_path=args.universe_profiles,
        recovery_path=args.recovery_targets,
    )
    bases = load_bases(
        args.bases, args.quotient_label, args.base_limit, args.base_offset
    )
    if not targets:
        raise ValueError("no current D4-fiber targets")
    if not bases:
        raise ValueError("no certified sextic bases")
    forms = coefficient_forms(
        args.coefficient_bound, args.form_extra, args.form_seed
    )
    constant_forms = [form for form in forms if not any(form[1:])]
    a_forms = constant_forms if args.a_mode == "constant" else forms
    b_forms = constant_forms if args.b_mode == "constant" else forms
    bivariate = PolynomialRing(QQ, names=("x", "y"))
    x, y = bivariate.gens()
    # Match the surviving bivariate variable name so Sage's canonical
    # multivariate-to-univariate conversion recognizes the eliminated norm.
    absolute_ring = PolynomialRing(QQ, "x")
    primes = [int(value) for value in prime_range(5, args.prime_max + 1)]
    started = time.monotonic()
    seen = set()
    counts = Counter()
    signature_counts = Counter()
    rows = []
    stopped = None
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        for base_index, base in enumerate(bases):
            q_coefficients = [ZZ(value) for value in base["coefficientLine"].split(",")]
            q = sum(QQ(value) * y**index for index, value in enumerate(q_coefficients))
            for a_tuple in a_forms:
                a = sum(QQ(value) * y**index for index, value in enumerate(a_tuple))
                for b_tuple in b_forms:
                    if counts["attempts"] >= args.max_candidates:
                        stopped = "max_candidates"
                        break
                    if time.monotonic() - started > args.max_wall_seconds:
                        stopped = "max_wall_seconds"
                        break
                    counts["attempts"] += 1
                    b = sum(QQ(value) * y**index for index, value in enumerate(b_tuple))
                    relative = x**4 - 2 * a * x**2 + a**2 - b
                    eliminated = absolute_ring(q.resultant(relative, y))
                    candidate = integral_monic_scale(eliminated, absolute_ring)
                    if candidate is None or candidate.degree() != 24:
                        continue
                    counts["degree24Monic"] += 1
                    if not candidate.is_irreducible():
                        continue
                    counts["irreducible"] += 1
                    real_roots = int(candidate.number_of_real_roots())
                    signature_counts[str(real_roots)] += 1
                    compatible = [
                        target for target in targets if real_roots in target["pairRs"]
                    ]
                    observed = []
                    for prime in primes:
                        profile = cycle_type(candidate, prime)
                        if profile is None:
                            continue
                        observed.append([prime, list(profile)])
                        compatible = [
                            target
                            for target in compatible
                            if profile in target["cycleProfiles"]
                        ]
                        if not compatible:
                            break
                    if not compatible:
                        continue
                    counts["profileCompatible"] += 1
                    if args.skip_reduction:
                        reduced = candidate
                    else:
                        try:
                            reduced = absolute_ring(pari(candidate).polredbest())
                        except Exception:
                            reduced = candidate
                    if (
                        reduced.degree() != 24
                        or reduced.leading_coefficient() != 1
                        or not reduced.is_irreducible()
                    ):
                        continue
                    line = coefficient_line(reduced)
                    digest = hashlib.sha256(line.encode("ascii")).hexdigest()
                    if digest in seen:
                        continue
                    seen.add(digest)
                    row = {
                        "aCoefficients": list(a_tuple),
                        "bCoefficients": list(b_tuple),
                        "base": base,
                        "baseIndex": base_index,
                        "coefficientSha256": digest,
                        "compatibleTargets": [
                            {
                                "label": target["label"],
                                "pairCount": len(target["pairRs"]),
                                "blockKernelOrder": target["blockKernelOrder"],
                                "groupOrder": target["groupOrder"],
                            }
                            for target in compatible
                        ],
                        "constructionFamily": "nested_d4",
                        "discriminantTwist": 0,
                        "observedFrobenius": observed,
                        "polynomial": line,
                        "r": real_roots,
                        "s": str(a_tuple),
                        "tParameter": str(b_tuple),
                    }
                    rows.append(row)
                    stream.write(json.dumps(row, sort_keys=True) + "\n")
                    stream.flush()
                if stopped:
                    break
            if stopped:
                break
    summary = {
        "schemaVersion": "rank11-d4-multiq-nested-pilot-v1",
        "quotientLabel": args.quotient_label,
        "targetLabels": [target["label"] for target in targets],
        "targetPairCount": sum(len(target["pairRs"]) for target in targets),
        "baseCount": len(bases),
        "formCount": len(forms),
        "aFormCount": len(a_forms),
        "bFormCount": len(b_forms),
        "aMode": args.a_mode,
        "bMode": args.b_mode,
        "counts": dict(counts),
        "signatureCounts": dict(sorted(signature_counts.items())),
        "resultRows": len(rows),
        "elapsedSeconds": time.monotonic() - started,
        "stopped": stopped,
        "output": str(args.output),
        "networkCalls": 0,
        "submissionCalls": 0,
    }
    temporary = args.summary.with_suffix(args.summary.suffix + ".tmp")
    temporary.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    temporary.replace(args.summary)
    print(json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
