#!/usr/bin/env sage -python
"""Search nested-quartic D4 fibers over exact 6T11 sextic bases.

For a sextic field generator y and elements a(y), b(y), the relative
quartic

    X^4 - 2*a*X^2 + a^2 - b

is generated by sqrt(a + sqrt(b)) and has generic D4 closure over the sextic
base.  Taking its norm to Q gives a degree-24 polynomial.  This pilot varies
small structured a and b, then matches exact Frobenius cycle types against
the exhaustive current 6T11/4T3 gold catalog.  It is offline and never
submits.
"""

from __future__ import annotations

import argparse
from functools import reduce
import hashlib
import json
from math import gcd
import time
from pathlib import Path

from sage.all import GF, PolynomialRing, QQ, ZZ, prime_range


ROOT = Path(__file__).resolve().parent


def coefficient_line(polynomial) -> str:
    return ",".join(str(ZZ(value)) for value in polynomial.list())


def sha256_line(line: str) -> str:
    return hashlib.sha256(line.encode()).hexdigest()


def primitive_monic(polynomial, ring):
    polynomial = ring(polynomial)
    denominator = ZZ(polynomial.denominator())
    coefficients = [ZZ(denominator * value) for value in polynomial.list()]
    content = reduce(gcd, (abs(int(value)) for value in coefficients if value), 0)
    if content:
        coefficients = [value // content for value in coefficients]
    integral = ring(coefficients)
    if integral.leading_coefficient() < 0:
        integral = -integral
    if integral.leading_coefficient() != 1:
        return None
    return integral


def cycle_type(polynomial, prime: int):
    reduced = polynomial.change_ring(GF(prime))
    if not reduced.is_squarefree():
        return None
    return tuple(
        sorted(
            int(factor.degree())
            for factor, exponent in reduced.factor()
            for _ in range(int(exponent))
        )
    )


def load_bases(path: Path, limit: int, offset: int = 0) -> list[dict]:
    bases = []
    seen = set()
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            row = json.loads(line)
            sextic = str(row["sextic"])
            if sextic in seen:
                continue
            seen.add(sextic)
            if len(seen) <= offset:
                continue
            bases.append(
                {
                    "parameters": {
                        key: row.get(key) for key in ("k", "m", "A", "B", "D")
                    },
                    "sextic": sextic,
                }
            )
            if len(bases) >= limit:
                break
    return bases


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bases",
        type=Path,
        default=ROOT / "data" / "p27_s4_wreath_6t11_pairnorm_km_n2_1_20260727.jsonl",
    )
    parser.add_argument(
        "--targets",
        type=Path,
        default=ROOT / "data" / "current_6t11_d4_gold_catalog_20260812.json",
    )
    parser.add_argument(
        "--universe-profiles",
        type=Path,
        help="optional exhaustive structural group profiles for safe matching",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "data" / "current_d4_6t11_nested_quartic_pilot_20260812.jsonl",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=ROOT / "data" / "current_d4_6t11_nested_quartic_pilot_20260812_summary.json",
    )
    parser.add_argument("--base-limit", type=int, default=24)
    parser.add_argument("--base-offset", type=int, default=0)
    parser.add_argument("--coefficient-bound", type=int, default=3)
    parser.add_argument(
        "--form-family",
        choices=("sparse", "mixed"),
        default="sparse",
        help="mixed adds linear-plus-quadratic a,b forms",
    )
    parser.add_argument("--prime-max", type=int, default=251)
    parser.add_argument("--max-candidates", type=int, default=12000)
    parser.add_argument("--max-wall-seconds", type=int, default=3600)
    args = parser.parse_args()

    target_payload = json.loads(args.targets.read_text(encoding="utf-8"))
    targets = []
    for row in target_payload["rows"]:
        targets.append(
            {
                "cycleProfiles": {
                    tuple(int(value) for value in profile)
                    for profile in row["cycleProfiles"]
                },
                "goldRs": {int(pair["r"]) for pair in row["goldPairs"]},
                "kernelOrders": [int(value) for value in row["kernelOrders"]],
                "label": str(row["label"]),
                "order": int(row["order"]),
            }
        )

    universe = None
    if args.universe_profiles:
        universe_payload = json.loads(
            args.universe_profiles.read_text(encoding="utf-8")
        )
        universe = [
            {
                "cycleProfiles": {
                    tuple(int(value) for value in profile)
                    for profile in row["cycleProfiles"]
                },
                "label": str(row["label"]),
                "order": int(row["order"]),
                "possibleRealRoots": {
                    int(value) for value in row["possibleRealRoots"]
                },
            }
            for row in universe_payload["groups"]
        ]
        universe_by_label = {row["label"]: row for row in universe}
    else:
        universe_by_label = {}

    bases = load_bases(args.bases, args.base_limit, args.base_offset)
    bnd = args.coefficient_bound
    constants = [value for value in range(-bnd, bnd + 1) if value]
    a_forms = []
    b_forms = []
    for c0 in range(-bnd, bnd + 1):
        for c1 in (-1, 1):
            a_forms.append((c0, c1, 0))
            b_forms.append((c0, c1, 0))
        a_forms.append((c0, 0, 1))
        b_forms.append((c0, 0, 1))
    for c0 in constants:
        b_forms.append((c0, 0, 0))
    if args.form_family == "mixed":
        for c0 in range(-bnd, bnd + 1):
            for c1 in (-1, 1):
                for c2 in (-1, 1):
                    a_forms.append((c0, c1, c2))
                    b_forms.append((c0, c1, c2))
    a_forms = sorted(set(a_forms))
    b_forms = sorted(set(b_forms))

    bivariate = PolynomialRing(QQ, names=("x", "y"))
    x, y = bivariate.gens()
    univariate = PolynomialRing(QQ, "x")
    primes = [int(value) for value in prime_range(5, args.prime_max + 1)]
    started = time.monotonic()
    seen = set()
    rows = []
    counts = {
        "attempts": 0,
        "degree24": 0,
        "distinct": 0,
        "irreducible": 0,
        "profileCompatible": 0,
        "signatureCounts": {},
        "uniqueGoldLabelMatches": 0,
    }
    stopped = None
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        for base_index, base in enumerate(bases):
            q_coefficients = [ZZ(value) for value in base["sextic"].split(",")]
            q = sum(QQ(value) * y**index for index, value in enumerate(q_coefficients))
            for a_tuple in a_forms:
                a = a_tuple[0] + a_tuple[1] * y + a_tuple[2] * y**2
                for b_tuple in b_forms:
                    if counts["attempts"] >= args.max_candidates:
                        stopped = "max_candidates"
                        break
                    if time.monotonic() - started > args.max_wall_seconds:
                        stopped = "max_wall_seconds"
                        break
                    counts["attempts"] += 1
                    b = b_tuple[0] + b_tuple[1] * y + b_tuple[2] * y**2
                    if b == 0:
                        continue
                    relative = x**4 - 2 * a * x**2 + a**2 - b
                    eliminated = q.resultant(relative, y)
                    candidate = primitive_monic(univariate(eliminated), univariate)
                    if candidate is None or candidate.degree() != 24:
                        continue
                    counts["degree24"] += 1
                    line = coefficient_line(candidate)
                    digest = sha256_line(line)
                    if digest in seen:
                        continue
                    seen.add(digest)
                    counts["distinct"] += 1
                    if not candidate.is_irreducible():
                        continue
                    counts["irreducible"] += 1
                    real_roots = int(candidate.number_of_real_roots())
                    counts["signatureCounts"][str(real_roots)] = (
                        counts["signatureCounts"].get(str(real_roots), 0) + 1
                    )
                    compatible = [row for row in targets if real_roots in row["goldRs"]]
                    compatible_all = (
                        [
                            row
                            for row in universe
                            if real_roots in row["possibleRealRoots"]
                        ]
                        if universe is not None
                        else None
                    )
                    observed = []
                    for prime in primes:
                        profile = cycle_type(candidate, prime)
                        if profile is None:
                            continue
                        observed.append([prime, list(profile)])
                        compatible = [
                            row for row in compatible if profile in row["cycleProfiles"]
                        ]
                        if compatible_all is not None:
                            compatible_all = [
                                row
                                for row in compatible_all
                                if profile in row["cycleProfiles"]
                            ]
                        if not compatible or compatible_all == []:
                            break
                    if not compatible:
                        continue
                    counts["profileCompatible"] += 1
                    if len(compatible) == 1:
                        counts["uniqueGoldLabelMatches"] += 1
                    output_row = {
                        "aCoefficients": list(a_tuple),
                        "bCoefficients": list(b_tuple),
                        "baseIndex": base_index,
                        "baseParameters": base["parameters"],
                        "coefficientSha256": digest,
                        "compatibleGoldLabels": [
                            {
                                "kernelOrders": row["kernelOrders"],
                                "label": row["label"],
                                "order": row["order"],
                            }
                            for row in compatible
                        ],
                        "compatibleAllLabels": (
                            [
                                {
                                    "label": row["label"],
                                    "order": row["order"],
                                }
                                for row in compatible_all
                            ]
                            if compatible_all is not None
                            else None
                        ),
                        "allMatchesLiveGold": (
                            all(
                                row["label"] in {item["label"] for item in compatible}
                                for row in compatible_all
                            )
                            if compatible_all is not None
                            else None
                        ),
                        "construction": "Norm_6T11/Q(X^4-2*a*X^2+a^2-b)",
                        "observedFrobenius": observed,
                        "polynomial": line,
                        "r": real_roots,
                        "sextic": base["sextic"],
                    }
                    rows.append(output_row)
                    stream.write(json.dumps(output_row, sort_keys=True) + "\n")
                    stream.flush()
                if stopped:
                    break
            if stopped:
                break

    summary = {
        "baseCount": len(bases),
        "bounds": {
            "baseLimit": args.base_limit,
            "baseOffset": args.base_offset,
            "coefficientBound": args.coefficient_bound,
            "formFamily": args.form_family,
            "maxCandidates": args.max_candidates,
            "maxWallSeconds": args.max_wall_seconds,
            "primeMax": args.prime_max,
        },
        "counts": counts,
        "elapsedSeconds": round(time.monotonic() - started, 3),
        "goldTargetLabels": len(targets),
        "goldTargetPairs": int(target_payload["goldPairCount"]),
        "networkCalls": 0,
        "output": str(args.output.resolve()),
        "resultRows": len(rows),
        "stopped": stopped,
        "submissionCalls": 0,
    }
    temporary = args.summary.with_suffix(args.summary.suffix + ".tmp")
    temporary.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    temporary.replace(args.summary)
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
