#!/usr/bin/env python3
"""Close calibrated Kummer characters under products and permutation sign.

Once two arithmetic generators in the same degree-12 field are calibrated,
their product realizes the sum of the corresponding quadratic characters.
Multiplication by ``f'(alpha)`` additionally toggles the permutation-sign
character.  This script forms those products inside ``Q(alpha)``, reduces
them modulo the defining polynomial, and calibrates every new squareclass.
It turns a few discovered character generators into as much of the complete
quadratic-character group as the arithmetic data supports.
"""

from __future__ import annotations

import argparse
import itertools
import json
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable, Sequence

from routeA.build_catalog_character_campaign import DEFAULT_MAP, load_jsonl
from routeA.build_t00035_campaign import _squarefree_part
from routeA.discover_linear_characters import DEFAULT_OUTPUT as DEFAULT_LINEAR
from routeA.discover_product_characters import (
    DEFAULT_OUTPUT as DEFAULT_PRODUCT,
    _seed_key,
    _squarefree_product,
    calibrate_character_seed,
)


DATA = Path(__file__).resolve().parent / "data"
DEFAULT_OUTPUT = DATA / "character_closure_discoveries.jsonl"
DEFAULT_CHECKED = DATA / "character_closure_discoveries_checked.json"


def _trim(values: Sequence[int | str | Fraction]) -> tuple[Fraction, ...]:
    output = [Fraction(value) for value in values]
    while len(output) > 1 and output[-1] == 0:
        output.pop()
    return tuple(output)


def _multiply_mod(
    left: Sequence[int | str | Fraction],
    right: Sequence[int | str | Fraction],
    modulus: Sequence[int | str | Fraction],
) -> tuple[Fraction, ...]:
    """Multiply ascending rational polynomials modulo a monic modulus."""

    degree = len(modulus) - 1
    rational_modulus = tuple(Fraction(value) for value in modulus)
    if degree <= 0 or rational_modulus[-1] != 1:
        raise ValueError("modulus must be monic of positive degree")
    output = [Fraction(0)] * (len(left) + len(right) - 1)
    for i, a in enumerate(left):
        for j, b in enumerate(right):
            output[i + j] += Fraction(a) * Fraction(b)
    output.extend([Fraction(0)] * max(0, degree + 1 - len(output)))
    for power in range(len(output) - 1, degree - 1, -1):
        leading = output[power]
        if not leading:
            continue
        offset = power - degree
        for index in range(degree + 1):
            output[offset + index] -= leading * rational_modulus[index]
    return _trim(output[:degree])


def _derivative(
    coefficients: Sequence[int | str | Fraction],
) -> tuple[Fraction, ...]:
    return _trim([
        power * Fraction(coefficients[power])
        for power in range(1, len(coefficients))
    ])


def _row_seed(row: dict[str, Any]) -> tuple[Fraction, ...]:
    if row.get("seed_coefficients") is not None:
        return _trim(tuple(row["seed_coefficients"]))
    shift = int(row["shift"])
    return (-shift, 1)


def _json_fraction(value: Fraction) -> int | str:
    value = Fraction(value)
    if value.denominator == 1:
        return value.numerator
    return f"{value.numerator}/{value.denominator}"


def character_closure_seeds(
    source_rows: Iterable[dict[str, Any]],
    *,
    map_path: str | Path = DEFAULT_MAP,
    bases: Iterable[int] = (),
) -> list[dict[str, Any]]:
    """Form every new squareclass generated by discoveries and sign."""

    map_by_base: dict[int, list[dict[str, Any]]] = {}
    for row in load_jsonl(map_path):
        map_by_base.setdefault(int(row["base_t"]), []).append(row)

    wanted = {int(value) for value in bases}
    grouped: dict[tuple[int, str, tuple[int, ...]], list[dict[str, Any]]] = {}
    for row in source_rows:
        if wanted and int(row["base_t"]) not in wanted:
            continue
        base = tuple(int(value) for value in row["base_coefficients"])
        key = int(row["base_t"]), str(row["label"]), base
        grouped.setdefault(key, []).append(row)

    output: list[dict[str, Any]] = []
    for (base_t, label, base), rows in grouped.items():
        # One compact arithmetic generator per locally identified character.
        # Rational norm squareclass alone is not an identity: two Kummer
        # modules with the same norm can realize different index-two groups.
        # The locally certified starting target distinguishes those modules;
        # retaining the norm as well preserves conjugate-character branches
        # that share a target label.
        generators: dict[tuple[int, int], tuple[Fraction, ...]] = {}
        for row in rows:
            norm_class = int(row["norm_squareclass"])
            character_target = int(
                row.get("starting_target_t", row.get("target_t", norm_class))
            )
            character_key = character_target, norm_class
            seed = _row_seed(row)
            current = generators.get(character_key)
            if current is None or (
                max(map(abs, seed)), len(seed)
            ) < (
                max(map(abs, current)), len(current)
            ):
                generators[character_key] = seed
        if not generators:
            continue
        disc_abs = int(rows[0]["disc_abs"])
        sign_class = abs(_squarefree_part(disc_abs))
        generator_rows = sorted(generators.items())

        # Products may have rational norm squareclass 1 or the discriminant
        # class without being trivial Kummer characters, so those classes
        # must be calibrated rather than discarded.  Only singleton source
        # generators and the sign generator itself are already known.
        best: dict[
            tuple[int, tuple[tuple[int, int], ...], bool],
            tuple[
                tuple[int | Fraction, ...],
                tuple[Fraction, ...],
            ],
        ] = {}
        for count in range(1, len(generator_rows) + 1):
            for subset in itertools.combinations(generator_rows, count):
                for include_sign in (False, True):
                    if count == 1 and not include_sign:
                        continue
                    norm_class = sign_class if include_sign else 1
                    seed = _derivative(base) if include_sign else (1,)
                    sources: list[tuple[int, int]] = []
                    for source_key, source_seed in subset:
                        source_target, source_class = source_key
                        norm_class = _squarefree_product(norm_class, source_class)
                        seed = _multiply_mod(seed, source_seed, base)
                        sources.append((int(source_target), int(source_class)))
                    rank = (
                        len(subset) + int(include_sign),
                        max(map(abs, seed)),
                        len(seed),
                    )
                    closure_key = (
                        int(norm_class),
                        tuple(sources),
                        bool(include_sign),
                    )
                    current = best.get(closure_key)
                    if current is None or rank < current[0]:
                        best[closure_key] = (
                            rank,
                            seed,
                        )

        targets = sorted({
            int(row["target_t"]) for row in map_by_base.get(base_t, [])
        })
        for (
            norm_class,
            sources,
            include_sign,
        ), (_, seed) in sorted(best.items()):
            output.append({
                "base_t": base_t,
                "label": label,
                "disc_abs": disc_abs,
                "base_coefficients": list(base),
                "seed_coefficients": [_json_fraction(value) for value in seed],
                "factor_shifts": [],
                "closure_source_squareclasses": [source[1] for source in sources],
                "closure_source_characters": [
                    {
                        "starting_target_t": source_target,
                        "norm_squareclass": source_class,
                    }
                    for source_target, source_class in sources
                ],
                "closure_includes_permutation_sign": include_sign,
                "norm_squareclass": int(norm_class),
                "candidate_target_ts": targets,
            })
    return sorted(
        output,
        key=lambda row: (
            int(row["base_t"]),
            str(row["label"]),
            len(row["closure_source_characters"]),
            int(row["closure_includes_permutation_sign"]),
            int(row["norm_squareclass"]),
            json.dumps(row["seed_coefficients"]),
        ),
    )


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", action="append", type=Path, default=[])
    parser.add_argument("--map", type=Path, default=DEFAULT_MAP)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--checked", type=Path, default=DEFAULT_CHECKED)
    parser.add_argument("--base", action="append", type=int, default=[])
    parser.add_argument("--limit", type=int)
    parser.add_argument("--options", type=int, default=2)
    parser.add_argument("--max-lifts", type=int, default=6)
    parser.add_argument("--coefficient-limit", type=int, default=10**120)
    parser.add_argument("--prime-limit", type=int, default=10000)
    args = parser.parse_args()

    source_paths = args.source or [DEFAULT_LINEAR, DEFAULT_PRODUCT]
    source_rows = [row for path in source_paths for row in load_jsonl(path)]
    seeds = character_closure_seeds(
        source_rows,
        map_path=args.map,
        bases=args.base,
    )
    if args.limit is not None:
        seeds = seeds[: max(0, args.limit)]

    discoveries = load_jsonl(args.output)
    checked = (
        set(json.loads(args.checked.read_text(encoding="utf-8")))
        if args.checked.exists()
        else set()
    )
    discovered_keys = {_seed_key(row) for row in discoveries}
    for index, seed in enumerate(seeds, 1):
        key = _seed_key(seed)
        if key in checked:
            continue
        successes, error = calibrate_character_seed(
            seed,
            options_per_signature=args.options,
            max_lifts=args.max_lifts,
            coefficient_limit=args.coefficient_limit,
            prime_limit=args.prime_limit,
        )
        distinct_starts = {row["starting_target_t"] for row in successes}
        calibrated = len(distinct_starts) == 1
        if calibrated and key not in discovered_keys:
            result = dict(seed)
            result.update(successes[0])
            result["calibration_kind"] = "character_squareclass_product_closure"
            discoveries.append(result)
            discovered_keys.add(key)
            _write_jsonl(args.output, discoveries)
        checked.add(key)
        args.checked.parent.mkdir(parents=True, exist_ok=True)
        args.checked.write_text(
            json.dumps(sorted(checked), indent=2) + "\n",
            encoding="utf-8",
        )
        print(json.dumps({
            "event": "character_closure_calibration",
            "index": index,
            "total": len(seeds),
            "base_t": seed["base_t"],
            "norm_squareclass": seed["norm_squareclass"],
            "calibrated": calibrated,
            "successes": successes,
            "error": error,
            "discoveries": len(discoveries),
        }, sort_keys=True), flush=True)

    print(json.dumps({
        "candidate_seeds": len(seeds),
        "checked": len(checked),
        "discoveries": len(discoveries),
        "output": str(args.output),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
