#!/usr/bin/env python3
"""Compatibility entry point for the extension-fingerprint matcher.

The former order/block-shape A/B/C proxy matcher was retired because it could
assign recipes to groups outside the construction's realizable extension
class.  Provide a capability catalog generated by GAP-aware construction code.
"""

from routeA.extension_matcher import main


if __name__ == "__main__":
    main()
